- Jenkinsfile
I updated the parent declaration in [pom](https://github.com/ivy-samples/ivy-project-demos/blob/master/DemosApp/pom.xml) which pointed on an old artifact that we renamed/removed (ch.ivyteam.ivy.build.config.dependencies).
Failing build: https://jenkins.ivyteam.io/job/ivy-project-demos/job/master/35/
Build with updated profile: https://jenkins.ivyteam.io/job/ivy-project-demos/job/master/36/
> XIVY-3123 Use correct maven profile

- ConnectivityDemos/ConnectivityDemos/pom.xml
- ConnectivityDemos/ConnectivityDemosRCPTest/pom.xml
- ConnectivityDemos/ConnectivityDemosTest/pom.xml
- ConnectivityDemos/pom.xml
- ErrorHandlingDemos/pom.xml
- HtmlDialogDemos/HtmlDialogDemos/pom.xml
- HtmlDialogDemos/HtmlDialogDemosTest/pom.xml
- HtmlDialogDemos/pom.xml
- QuickStartTutorial/pom.xml
- WorkflowDemos/WorkflowDemos/pom.xml
- WorkflowDemos/WorkflowDemosTest/pom.xml
- WorkflowDemos/pom.xml
- build.maven/iar/pom.xml
- build.maven/iar/web.test/pom.xml
- build.maven/job/update-version/pom.xml
- build.maven/pom.xml
- build.maven/rcptt/pom.xml
- pom.xml
Build is green: https://jenkins.ivyteam.io/job/ivy-project-demos/job/downgrade_to_8.0.1/
> Downgrade version from 9.1.0-SNAP to 8.0.1-SNAP

- ConnectivityDemos/ConnectivityDemosTest/src_test/rest/bpm/TestDataMapping.java
Because ManagedBpmAccess was removed in master we have to remove it also from demo projects
> XIVY-3563 Remove ManagedBpmAccess from bpm tests in demo projects

- WorkflowDemos/WorkflowDemosTest/src_test/test/bpm/TestStartProcessAs.java
Shows how to use as() API. 
This may not be the final approach how to demo the API. But for now I can test if this works as expected and use it at the review. 
Was not able to run the TestProcurementProcess yet.
This has a dependency to the branch https://bitbucket.org/axonivy-prod/ivy-core/branch/feature/XIVY-3562_add_as_tests_to_demo_projects
> XIVY-3562 Add test to demo as() API

- build.maven/job/update-version/pom.xml
found another zugpronexus repo...
But honestly does anyone use this update-version maven execution? This will never run on any pc except we deploy the maven-version-plugin on repo.axonivy.com... And in my opinion this should never run on any pc (or even be on this github repo). I use always VSCode Search/Replace for a version update...
I vote for complete removal of this update-version part!
But anyway here s the fix to use the new nexus.ivyteam.io repo.
> XIVY-3574 fix old maven repo

- connectivity/connectivity-demos/webContent/js/ivy.js
- was no longer compatible to current master (9.1)
> XIVY-3867 fix: chat resource URI in JS

- build.maven/web/pom.xml
- downgrade to M4 surefire plugin which does not log these kind of warnings
- as soon as 9.1 is released we can switch to the 9.1.1 project-build-plugin snap that addresses this issue correctly.
> XIVY-494 fix: reflection warnings in build pipeline

- README.md
- raise-version.sh
I will provide in all repos a `raise-version.sh` script. There you can pass as first argument the new version number. We don't explain our common approach in all README.md in all repos anymore.
> Provide a common raise-version.sh script

- connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/client/file/FileUpload.java
see org.glassfish.jersey.media.multipart.internal.MultiPartWriter.writeTo(MultiPart,
Class<?>, Type, Annotation[], MediaType, MultivaluedMap<String, Object>,
OutputStream)
> reduce complexity: mime+boundary is set by MultiPartWriter

- connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/aynch/chat/ChatService.java
- connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/provider/ApiConstants.java
- connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/provider/ApprovalService.java
- connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/provider/BatchService.java
- connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/provider/FileService.java
- connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/provider/PersonService.java
- connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/provider/SecureService.java
... helps to separate them from other services once the
connectivity-demos is published among other endpoints to a wf-app.
> XIVY-4019 cluster services under a 'demo' tag

- workflow/workflow-demos/processes/Signal/NewEmployee.mod
if not executed as Developer user (e.g on engine), this user had never not enough rights (CaseWirteName missing) to execute process, so I add execute with system rights to script step
> fix signal workflow process for engine

- connectivity/connectivity-demos-test/pom.xml
- currently swaggers service reurns an invalid pet list : so don't get
distracted by jackson deserializer warnings
- however; we should run against our own infrastructure anway.
> fix test: json returned by public PetStore is corrupt

- html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/output/DocumentViewer/DocumentViewer.xhtml
- html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/output/DocumentViewer/embedded-viewer.xhtml
Because the underling pdf.js of the PrimeFaces Extensions Document
Viewer is outdated and renders some PDFs not correctly on newest
browsers
> XIVY-6624 Show how to use the browser native pdf viewer

- connectivity/connectivity-demos-test/config/webservice-clients.yaml
- policy setup should be done once per client: here we switch it for
tests ... so the cache won't work.
> XIVY-6566 disable endpoint.cache: as we modify assertion properties

- Jenkinsfile
This reverts commit b162cfc471c706139a0ef6e093d6a2b9d0f5860d.
- problem will no longer be exposed by the project-build-plugin
> Revert "XIVY-7639 fix: exclude real existing validation problem"

- connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/json/OpenApiJsonFeature.java
- yet we can't use the suggested builder, as we get the objectMapper
from the JAX-RS stack
> adapt to Jackson 2.13

- Dockerfile
- connectivity/connectivity-demos-test/pom.xml
- docker-entrypoint.sh
- workflow/workflow-demos-test/pom.xml
FYI;
- I've upgraded commons-text in core to latest, which requires commons.lang3 latest.
- here we have maven dependencies in test which has an older commons.lang3 version (transitiv)
- result: really strange errors, but only in maven build not by executing test in Axon Ivy Designer
Biggest pain point:
- Maven build behaves different than executing test in Axon Ivy Designer
I've the feeling that this kind of issues will come back to us, if our users are going to write tests.
> Use latest commons-lang3 to have no clashes with dep hierarchy

- connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/aynch/SignalInvoker.java
signalInvoker used deprecated public API methods
https://github.com/axonivy/core/pull/6787
> XIVY-5504 fix signalInvoker used deprecated public API methods

- connectivity/connectivity-demos-product/zip.xml
- demos-app/demos-app-product/zip.xml
- error-handling/error-handling-demos-product/zip.xml
- html-dialog/html-dialog-demos-product/zip.xml
- quick-start-tutorial/quick-start-tutorial-product/zip.xml
- rule-engine/rule-engine-demos-product/zip.xml
- workflow/workflow-demos-product/zip.xml
Included README_DE.md in pom.xml and zip.xml
> MARP-1333 Missing setup path for README_DE.md

- Jenkinsfile
Any reason why this is like this?
Currently, the demo-projects are only deployed on `master`, `release/8.0` and `release/9.3`...
> Fix deploy on release branch

- .github/workflows/ci.yml
- We run the tests on our own Jenkins CI
- There are some tests which are currently failing on GitHub Actions, however the current shared actions workflow yml has to strict glob patters and don't find the surefire raport XML
e.g:
```
[INFO] -------------------------------------------------------
[INFO]  T E S T S
[INFO] -------------------------------------------------------
[INFO] Running workflow.trigger.WebTestCreateNewEmployeeIT
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 7.368 s -- in workflow.trigger.WebTestCreateNewEmployeeIT
[INFO] Running workflow.businessdata.WebTestBusinessDataIT
[INFO] Tests run: 2, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 8.403 s -- in workflow.businessdata.WebTestBusinessDataIT
[INFO] Running …
```
> Disable tests on GitHub Actions

- connectivity/connectivity-demos-test/pom.xml
I've updated jersey. When somebody is using the jersey library in the test project, he will also need to update it. Because it gets mixed with the classpath of the engine.
Something  which was ever since the case, and we are working on it to improve this in future. 
Still some tests are failing, I need to investigate why, But now there are less tests failing. :)
> Raise jersey client in test to align with version of platform

- connectivity/connectivity-demos-test/pom.xml
- workflow/workflow-demos-test/pom.xml
first fruits of the parent-pom introduction :clap: 
... fixes warnings :warning: ... due to otherwise re-declared managed versions
> fix: remove version re-declaration of managed deps

- connectivity/connectivity-demos/.classpath
- connectivity/connectivity-demos/.gitignore
- connectivity/connectivity-demos/pom.xml
fix the build: src_generated is now automatically 'cleaned' on project-build-plugin:compile ... therefore we use another src_dir for restServiceClient codegen artifacts.
> distinct src_generated dir

- .github/workflows/ci.yml
- connectivity/connectivity-demos-test/pom.xml
- connectivity/connectivity-demos/pom.xml
- error-handling/error-handling-demos/pom.xml
- html-dialog/html-dialog-demos-test/pom.xml
- html-dialog/html-dialog-demos/pom.xml
- quick-start-tutorial/quick-start-tutorial/pom.xml
- rule-engine/rule-engine-demos-test/pom.xml
- rule-engine/rule-engine-demos/pom.xml
- workflow/workflow-demos-test/pom.xml
- workflow/workflow-demos/pom.xml
use a released version, in order to bypass '-SNAPSHOT' restriction of maven-release-plugin.
> freeze project-build-plugin to 12.0.5 for LTS release
