HtmlDialogDemos/HtmlDialogDemos/src/ch/ivyteam/htmldialog/demo/component/PersonLazyDataModel.java
- RCPTT checks if the project does not have any warnings or errors
=> Suppress serializable warning on PersonLazyDataModel

ConnectivityDemos/ConnectivityDemos/.classpath, ConnectivityDemos/ConnectivityDemos/dataclasses/com/axonivy/connectivity/rest/OpenApiData.ivyClass, ConnectivityDemos/ConnectivityDemos/pom.xml, ConnectivityDemos/ConnectivityDemos/processes/rest/openapi.mod, ConnectivityDemos/ConnectivityDemos/restClients.restConfig, ConnectivityDemos/ConnectivityDemos/src/com/axonivy/connectivity/rest/sample/petstore/swagger.json, ConnectivityDemos/ConnectivityDemosRCPTest/tests/rest/ExecuteRestMapping.test
A first glance at https://jira.axonivy.com/confluence/display/XIVY/Powerfull+connectors
.... in 8.0 LTS compatible manor.
=> Feature/xivy 3508 open.api pojo.gen.demo

HtmlDialogDemos/HtmlDialogDemos/src/ch/ivyteam/htmldialog/demo/component/UserConverter.java
HtmlDialogDemo has a deprecation warning: https://jenkins.ivyteam.io/view/Scrum%20Master/job/ivy-core_test-rcptt-windows-ci/job/master/101/artifact/test/designer-rcptt/target/results/images/%20%208.png
Build: https://jenkins.ivyteam.io/job/ivy-project-demos/job/feature%252FXIVY-3535_htmlDemo/
=> XIVY-3535 Use new user API in HtmlDialogDemo

ConnectivityDemos/ConnectivityDemos/pom.xml, DemosApp/pom.xml, ErrorHandlingDemos/pom.xml, HtmlDialogDemos/HtmlDialogDemos/pom.xml, QuickStartTutorial/pom.xml, WorkflowDemos/WorkflowDemos/pom.xml, build.maven/iar/pom.xml
Build: https://jenkins.ivyteam.io/job/ivy-project-demos/job/feature%252FXIVY-3138_use-project-build-plugin-v8.0.3/
=> XIVY-3138 Use project build plugin version 8.0.3 release

HtmlDialogDemos/HtmlDialogDemos/src/ch/ivyteam/htmldialog/demo/theme/GuestPreferences.java, HtmlDialogDemos/HtmlDialogDemos/webContent/layouts/BootstrapDemo.xhtml, HtmlDialogDemos/HtmlDialogDemos/webContent/layouts/HtmlDemo.xhtml, HtmlDialogDemos/HtmlDialogDemos/webContent/layouts/includes/topbar.xhtml
Fix theme switcher. Only serenity themes (others can not render menu)
=> XIVY-3530 fix theme switcher

HtmlDialogDemos/HtmlDialogDemos/src/ch/ivyteam/htmldialog/demo/theme/GuestPreferences.java
Fix rcptt & ivy-project-demos builds
=> XIVY-3530 Fix serialization warning

Jenkinsfile
=> XIVY-3565 adjust pipeline for release/8.0

ConnectivityDemos/ConnectivityDemosTest/src_test/rest/bpm/TestDataMapping.java, WorkflowDemos/WorkflowDemosTest/src_test/test/bpm/TestStartProcessAs.java
can be merged as soon as new API is in core: see https://bitbucket.org/axonivy-prod/ivy-core/pull-requests/1700/feature-xivy-3562-apisugar-requestby
=> XIVY-3562 sugar: use new request().path() API

Jenkinsfile, build.maven/iar/pom.xml
project-demos 8.0
Build: https://jenkins.ivyteam.io/job/ivy-project-demos/job/feature%252FXIVY-3774_checkVersions/
=> XIVY-3774 Check project-build-plugin for new version

ConnectivityDemos/ConnectivityDemosTest/src_test/rest/bpm/TestDataMapping.java, WorkflowDemos/WorkflowDemosTest/src_test/test/bpm/TestProcurementRequest.java, WorkflowDemos/WorkflowDemosTest/src_test/test/bpm/TestStartProcessAs.java
BUILD https://jenkins.ivyteam.io/job/ivy-project-demos/job/feature%252FXIVY-3754-bpmError/
=> XIVY-3754 adapt to new unchecked exception API

ConnectivityDemos/ConnectivityDemosTest/dataclasses/com/axonivy/connectivity/test/CreateApprovalData.ivyClass, ConnectivityDemos/ConnectivityDemosTest/processes/rest/testApprovalCreation.mod, ConnectivityDemos/ConnectivityDemosTest/src_test/rest/bpm/TestApprovalCallSub.java
- verify that we are able to call a sub starting in a remote project.
=> XIVY-3754 integration tests call sub with bpmClient call

connectivity/connectivity-demos/processes/rest/uiPath.mod
- do not cause confusion with fancy icons:
wait for https://jira.axonivy.com/jira/browse/XIVY-4049
to make these elements sexy.
=> XIVY-4052 use standard icons for REST

connectivity/connectivity-demos-rcptt-test/Jenkinsfile
build has failed on a test failure, now it will be unstable
=> fix jenkins rcptt build

connectivity/connectivity-demos/pom.xml
build wants newest versions of dependecies
=> raise swagger codegen to 3.0.20

connectivity/connectivity-demos-test/pom.xml, connectivity/connectivity-demos/pom.xml
Builds:
https://jenkins.ivyteam.io/job/ivy-project-demos/job/feature%252FXIVY-4014_upgrade_to_jersey_2_31/
=> XIVY-4014 Upgrade to jersey 2.31

workflow/workflow-demos-test/src_test/test/bpm/TestBusinessCaseDataWorkflow.java, workflow/workflow-demos-test/src_test/test/bpm/TestProcurementRequest.java
- wrap similar constants behind an interface
- divide data/exec/assertions into extra methods
- use static methods where possible
=> XIVY-4158 polish @IvyProcessTests for release 9.1

connectivity/connectivity-demos-test/src/com/axonivy/connectivity/rest/json/releases.json, connectivity/connectivity-demos-test/src/com/axonivy/connectivity/rest/json/robots.json, connectivity/connectivity-demos/processes/rest/uiPath.mod
- use query filter params to reduce unnecessary REST objects transfers
which will never be used on the client side.
- moreover it gives a basic idea how ODATa services provide filter
capabilities.
=> XIVY-4510 demonstrate UiPath query filters

connectivity/connectivity-demos/.classpath, connectivity/connectivity-demos/pom.xml
- which is now public accessible.
=> XIVY-3508 use ivy-core JSR310 jar

rule-engine/rule-engine-demos/src_hd/rule/engine/demo/DiscountCalculator/DiscountCalculatorProcess.mod
- Use new Rule process element to apply DRL rules
- Added annotation about Java API when defining multiple namespaces
Now looks like this:
=> XIVY-2588 Update rule engine demo to use new process element

html-dialog/html-dialog-demos-test/src_test/ch/ivyteam/htmldialog/demo/WebTestIcons.java, html-dialog/html-dialog-demos/processes/Primefaces.mod, html-dialog/html-dialog-demos/webContent/js/ivyicons-showcase.js, html-dialog/html-dialog-demos/webContent/layouts/HtmlDemo.xhtml, html-dialog/html-dialog-demos/webContent/layouts/includes/sidebar.xhtml, html-dialog/html-dialog-demos/webContent/layouts/styles/ivyicons-showcase.css, html-dialog/html-dialog-demos/webContent/view/ivyicons.xhtml
=> XIVY-4905 add ivyicons showcase

build.maven/test/pom.xml, connectivity/connectivity-demos/pom.xml, error-handling-demos/pom.xml, html-dialog/html-dialog-demos/pom.xml, quick-start-tutorial/pom.xml, rule-engine/rule-engine-demos/pom.xml, serenity/serenity-showcase/pom.xml, workflow/workflow-demos/pom.xml
Test of project build plugin raise pipeline
=> Raise version to 9.1.1-SNAPSHOT

connectivity/connectivity-demos-test/pom.xml
- system scoped deps are deprecated anyway
=> XIVY-6602 add local CXF client without using 'system' scoped deps

html-dialog/html-dialog-demos-test/src_test/ch/ivyteam/htmldialog/demo/WebTestOutput.java, html-dialog/html-dialog-demos/processes/Output.mod, html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/output/DocumentViewer/DocumentViewer.rddescriptor, html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/output/DocumentViewer/DocumentViewer.xhtml, html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/output/DocumentViewer/DocumentViewerData.ivyClass, html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/output/DocumentViewer/DocumentViewerProcess.mod, html-dialog/html-dialog-demos/webContent/layouts/includes/sidebar.xhtml
new demo with the pe:documentviewer. Upload a pdf docuemnt to be shown in the viewer. 
incl. a  test
=> Add documentviewer demo

connectivity/connectivity-demos/config/rest-clients.yaml, connectivity/connectivity-demos/config/webservice-clients.yaml
simplify and streamline configs that reference engine internals
=> XIVY-6363 use new config expressions

connectivity/connectivity-demos-test/src/com/axonivy/connectivity/rest/UserCreator.java, html-dialog/html-dialog-demos/src/ch/ivyteam/htmldialog/demo/component/UserConverter.java, html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/output/AutoCompleteDemo/AutoCompleteDemoProcess.mod, workflow/workflow-demos-test/processes/InitializeTestEnvironment.mod, workflow/workflow-demos-test/src_test/test/bpm/TestStartProcessAs.java, workflow/workflow-demos/src_hd/workflow/agileBPM/define_WF/define_WF.xhtml, workflow/workflow-demos/src_hd/workflow/agileBPM/define_WF/define_WFProcess.mod, workflow/workflow-demos/src_hd/workflow/agileBPM/define_WF/responsableUser.xhtml, workflow/workflow-demos/src_hd/workflow/agileBPM/task_Form/add_task.xhtml, workflow/workflow-demos/src_hd/workflow/agileBPM/task_Form/case_info.xhtml, workflow/workflow-demos/src_hd/workflow/agileBPM/task_Form/task_FormProcess.mod
Use new ivy.security API were possible
Replace usage of deprecated methods with new API
=> XIVY-3570 Use new ivy.security API were possible

connectivity/connectivity-demos/processes/rest/openapi.mod, html-dialog/html-dialog-demos/processes/Component.mod, html-dialog/html-dialog-demos/processes/Demo.mod, html-dialog/html-dialog-demos/processes/Input.mod, html-dialog/html-dialog-demos/processes/Offline.mod, html-dialog/html-dialog-demos/processes/Other.mod, html-dialog/html-dialog-demos/processes/Output.mod, html-dialog/html-dialog-demos/processes/Primefaces.mod, html-dialog/html-dialog-demos/processes/Static.mod, serenity/serenity-showcase/processes/Main.mod
Open HtmlDialogDemo process starts and the Serenity Showcase in full screen per default.
=> XIVY-7185 Define which starts should be opened in fullscreen per default

Jenkinsfile
- we know that our connectivity-demos are shipped with a validation warning.
=> XIVY-7639 fix: exclude real existing validation problem

html-dialog/html-dialog-demos/webContent/js/icons-showcase.js, html-dialog/html-dialog-demos/webContent/layouts/styles/icons-showcase.css, html-dialog/html-dialog-demos/webContent/view/icons.xhtml
- Add primeicons
- Deprecate material icons
- Update font-awesome to 6.1
=> Fix icon showcase for streamline jar

html-dialog/html-dialog-demos/src/ch/ivyteam/htmldialog/demo/component/PersonLazyDataModel.java, html-dialog/html-dialog-demos/src/ch/ivyteam/htmldialog/demo/component/PersonLazySorter.java, html-dialog/html-dialog-demos/src/ch/ivyteam/htmldialog/demo/data/DataSource.java
honestly these filter yet, not work as they should. And the impl doesn't look as we've invented it :rice_cracker: 
so I'll just do this minor refactoring to comply with pf11 yet.
=> XIVY-8036 comply with primefaces 11

connectivity/connectivity-demos/pom.xml, workflow/workflow-demos/src/ch/ivyteam/ivy/wfdemo/businessdata/AbstractBusinessDataLazyDataModel.java
=> XIVY-8036 migrate to PF11 lazy-date model

connectivity/connectivity-demos-test/processes/rest/config.p.json, connectivity/connectivity-demos-test/src_test/com/axonivy/connectivity/rest/WebTestRestProcessStarts.java, connectivity/connectivity-demos-test/src_test/soap/bpm/TestDataMapping.java
- smartbear is unable to deliver valid results due to a insufficient
disk-space
=> used mocked replacement of Smartbares Testservice

connectivity/connectivity-demos-test/.settings/ch.ivyteam.ivy.designer.prefs, connectivity/connectivity-demos/.settings/ch.ivyteam.ivy.designer.prefs, error-handling/error-handling-demos/.settings/ch.ivyteam.ivy.designer.prefs, html-dialog/html-dialog-demos-test/.settings/ch.ivyteam.ivy.designer.prefs, html-dialog/html-dialog-demos/.settings/ch.ivyteam.ivy.designer.prefs, quick-start-tutorial/quick-start-tutorial/.settings/ch.ivyteam.ivy.designer.prefs, rule-engine/rule-engine-demos-test/.settings/ch.ivyteam.ivy.designer.prefs, rule-engine/rule-engine-demos/.settings/ch.ivyteam.ivy.designer.prefs, workflow/workflow-demos-test/.settings/ch.ivyteam.ivy.designer.prefs, workflow/workflow-demos/.settings/ch.ivyteam.ivy.designer.prefs
- applies resurrected LTS8 CXF to -> LE CXF param mappings
=> XIVY-8150 migrate to project version 94.002

html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/input/TextEditorDemo/TextEditorDemo.xhtml, html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/offline/ClientSideValidation/ClientSideValidation.xhtml
There are only two ui-icon-* in the whole repo. Seems not to be as big of a problem as I thought. Never the less let's replace them.
=> XIVY-8401 replace ui-icon-check with pi pi-check icon

workflow/workflow-demos/processes/CaseMap/Lending.icm
Groupid has been changed from ch.ivyteam to com.axonivy
=> Fix groupid in Lending case map

error-handling/error-handling-demos/processes/Approval.p.json, html-dialog/html-dialog-demos/processes/Demo.p.json, quick-start-tutorial/quick-start-tutorial/processes/MyProcess.p.json, rule-engine/rule-engine-demos/processes/DiscountCalculator.p.json, workflow/workflow-demos/processes/Humantask/ProcurementRequestUserTask.p.json
As found with Tobias, it is easier if we have a start point for each demo project.
=> XIVY-9212 added demo tag to various demo starts

connectivity/connectivity-demos-test/pom.xml, connectivity/connectivity-demos/pom.xml, error-handling/error-handling-demos/pom.xml, html-dialog/html-dialog-demos-test/pom.xml, html-dialog/html-dialog-demos/pom.xml, quick-start-tutorial/quick-start-tutorial/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, rule-engine/rule-engine-demos/pom.xml, workflow/workflow-demos-test/pom.xml, workflow/workflow-demos/pom.xml
Raising project-build-plugin version to 9.4.1 / 9.4.2-SNAPSHOT
=> Raising project-build-plugin version to 9.4.1 / 9.4.2-SNAPSHOT

connectivity/connectivity-demos-product/pom.xml, connectivity/connectivity-demos-test/pom.xml, connectivity/connectivity-demos/pom.xml, connectivity/pom.xml, demos-app/demos-app-product/pom.xml, demos-app/demos-app/pom.xml, demos-app/pom.xml, error-handling/error-handling-demos-product/pom.xml, error-handling/error-handling-demos/pom.xml, error-handling/pom.xml, html-dialog/html-dialog-demos-product/pom.xml, html-dialog/html-dialog-demos-test/pom.xml, html-dialog/html-dialog-demos/pom.xml, html-dialog/pom.xml, pom.xml, quick-start-tutorial/pom.xml, quick-start-tutorial/quick-start-tutorial-product/pom.xml, quick-start-tutorial/quick-start-tutorial/pom.xml, rule-engine/pom.xml, rule-engine/rule-engine-demos-product/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, rule-engine/rule-engine-demos/pom.xml, workflow/pom.xml, workflow/workflow-demos-product/pom.xml, workflow/workflow-demos-test/pom.xml, workflow/workflow-demos/pom.xml
Raise version to 10.0.0-SNAPSHOT
=> Raise version to 10.0.0-SNAPSHOT

connectivity/connectivity-demos-test/pom.xml, connectivity/connectivity-demos/pom.xml, error-handling/error-handling-demos/pom.xml, html-dialog/html-dialog-demos-test/pom.xml, html-dialog/html-dialog-demos/pom.xml, quick-start-tutorial/quick-start-tutorial/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, rule-engine/rule-engine-demos/pom.xml, workflow/workflow-demos-test/pom.xml, workflow/workflow-demos/pom.xml
Raising project-build-plugin version to 9.4.1 / 10.0.0-SNAPSHOT
=> Raising project-build-plugin version to 9.4.1 / 10.0.0-SNAPSHOT

html-dialog/html-dialog-demos-test/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, workflow/workflow-demos-test/pom.xml
Raising web-tester version to 10.0.0
=> Raising web-tester version to 10.0.0

connectivity/connectivity-demos-product/pom.xml, connectivity/connectivity-demos-test/pom.xml, connectivity/connectivity-demos/pom.xml, connectivity/pom.xml, demos-app/demos-app-product/pom.xml, demos-app/demos-app/pom.xml, demos-app/pom.xml, error-handling/error-handling-demos-product/pom.xml, error-handling/error-handling-demos/pom.xml, error-handling/pom.xml, html-dialog/html-dialog-demos-product/pom.xml, html-dialog/html-dialog-demos-test/pom.xml, html-dialog/html-dialog-demos/pom.xml, html-dialog/pom.xml, pom.xml, quick-start-tutorial/pom.xml, quick-start-tutorial/quick-start-tutorial-product/pom.xml, quick-start-tutorial/quick-start-tutorial/pom.xml, rule-engine/pom.xml, rule-engine/rule-engine-demos-product/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, rule-engine/rule-engine-demos/pom.xml, workflow/pom.xml, workflow/workflow-demos-product/pom.xml, workflow/workflow-demos-test/pom.xml, workflow/workflow-demos/pom.xml
Raise version to 11.1.0-SNAPSHOT
=> Raise version to 11.1.0-SNAPSHOT

connectivity/connectivity-demos-test/pom.xml, connectivity/connectivity-demos/pom.xml, error-handling/error-handling-demos/pom.xml, html-dialog/html-dialog-demos-test/pom.xml, html-dialog/html-dialog-demos/pom.xml, quick-start-tutorial/quick-start-tutorial/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, rule-engine/rule-engine-demos/pom.xml, workflow/workflow-demos-test/pom.xml, workflow/workflow-demos/pom.xml
Raising project-build-plugin version to 10.0.0 / 11.1.0-SNAPSHOT
=> Raising project-build-plugin version to 10.0.0 / 11.1.0-SNAPSHOT

html-dialog/html-dialog-demos-test/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, workflow/workflow-demos-test/pom.xml
Raising web-tester version to 11.1.0
=> Raising web-tester version to 11.1.0

connectivity/connectivity-demos-test/pom.xml, connectivity/connectivity-demos/pom.xml, error-handling/error-handling-demos/pom.xml, html-dialog/html-dialog-demos-test/pom.xml, html-dialog/html-dialog-demos/pom.xml, quick-start-tutorial/quick-start-tutorial/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, rule-engine/rule-engine-demos/pom.xml, workflow/workflow-demos-test/pom.xml, workflow/workflow-demos/pom.xml
Raising project-build-plugin version to 11.1.0 / 11.2.0-SNAPSHOT
=> Raising project-build-plugin version to 11.1.0 / 11.2.0-SNAPSHOT

connectivity/connectivity-demos-test/.settings/ch.ivyteam.ivy.designer.prefs, connectivity/connectivity-demos/.settings/ch.ivyteam.ivy.designer.prefs, error-handling/error-handling-demos/.settings/ch.ivyteam.ivy.designer.prefs, html-dialog/html-dialog-demos-test/.settings/ch.ivyteam.ivy.designer.prefs, html-dialog/html-dialog-demos/.settings/ch.ivyteam.ivy.designer.prefs, quick-start-tutorial/quick-start-tutorial/.settings/ch.ivyteam.ivy.designer.prefs, rule-engine/rule-engine-demos-test/.settings/ch.ivyteam.ivy.designer.prefs, rule-engine/rule-engine-demos/.settings/ch.ivyteam.ivy.designer.prefs, workflow/workflow-demos-test/.settings/ch.ivyteam.ivy.designer.prefs, workflow/workflow-demos/.settings/ch.ivyteam.ivy.designer.prefs
Raise ivy projects to latest version
=> Raise ivy projects to latest version

connectivity/connectivity-demos-product/pom.xml, connectivity/connectivity-demos-test/pom.xml, connectivity/connectivity-demos/pom.xml, connectivity/pom.xml, demos-app/demos-app-product/pom.xml, demos-app/demos-app/pom.xml, demos-app/pom.xml, error-handling/error-handling-demos-product/pom.xml, error-handling/error-handling-demos/pom.xml, error-handling/pom.xml, html-dialog/html-dialog-demos-product/pom.xml, html-dialog/html-dialog-demos-test/pom.xml, html-dialog/html-dialog-demos/pom.xml, html-dialog/pom.xml, pom.xml, quick-start-tutorial/pom.xml, quick-start-tutorial/quick-start-tutorial-product/pom.xml, quick-start-tutorial/quick-start-tutorial/pom.xml, rule-engine/pom.xml, rule-engine/rule-engine-demos-product/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, rule-engine/rule-engine-demos/pom.xml, workflow/pom.xml, workflow/workflow-demos-product/pom.xml, workflow/workflow-demos-test/pom.xml, workflow/workflow-demos/pom.xml
Raise version to 11.2.0-SNAPSHOT
=> Raise version to 11.2.0-SNAPSHOT

connectivity/connectivity-demos-test/pom.xml, connectivity/connectivity-demos/pom.xml, error-handling/error-handling-demos/pom.xml, html-dialog/html-dialog-demos-test/pom.xml, html-dialog/html-dialog-demos/pom.xml, quick-start-tutorial/quick-start-tutorial/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, rule-engine/rule-engine-demos/pom.xml, workflow/workflow-demos-test/pom.xml, workflow/workflow-demos/pom.xml
Raising project-build-plugin version to 10.0.6 / 10.0.7-SNAPSHOT
=> Raising project-build-plugin version to 10.0.6 / 10.0.7-SNAPSHOT

connectivity/connectivity-demos/processes/rest/callOwnPersonRestService.p.json, connectivity/connectivity-demos/processes/rest/dataMapping.p.json, connectivity/connectivity-demos/src_hd/com/axonivy/connectivity/rest/PersonManager/PersonManagerProcess.p.json
- fix rest processes broken by early json refactoring
=> re-convert to latest 11.1 json from r10

connectivity/connectivity-demos/pom.xml
This reverts commit 3950153d12ff8097a9e4c0fd678b9ee712e78b93.
=> Revert "Bump jsonschema2pojo-maven-plugin from 1.2.0 to 1.2.1"

Jenkinsfile
4.11 seems to have a problem with the session on firefox
=> Fix selenium version to 4.10

connectivity/connectivity-demos-test/src_test/com/axonivy/connectivity/rest/IntegrationTestRestfulDateResource.java, connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/json/BackendJsonMapperCustomization.java, connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/provider/DateResource.java
shed some light on how to customize rest-resource object-mappers: 
https://axonivy.zendesk.com/agent/tickets/3560
=> demonstrate a global customer json-mapper for resources

error-handling/error-handling-demos/processes/Booking/Booking.p.json, error-handling/error-handling-demos/processes/Booking/Service/Car.p.json, error-handling/error-handling-demos/processes/Booking/Service/Flight.p.json
- Refactor error handling demo from WebServiceCall activities to Scripts
=> Fix new missing webservice client id warning

connectivity/connectivity-demos-test/pom.xml
Updated jackson in the core to latest version.
=> Raise jersey client to 2.41

connectivity/connectivity-demos-test/pom.xml, html-dialog/html-dialog-demos-test/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, workflow/workflow-demos-test/pom.xml
Raising web-tester version to 11.2.0
=> Raising web-tester version to 11.2.0

connectivity/connectivity-demos-test/pom.xml, html-dialog/html-dialog-demos-test/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, workflow/workflow-demos-test/pom.xml
Raising web-tester version to 11.2.1
=> Raising web-tester version to 11.2.1

connectivity/connectivity-demos-test/pom.xml, connectivity/connectivity-demos/pom.xml, error-handling/error-handling-demos/pom.xml, html-dialog/html-dialog-demos-test/pom.xml, html-dialog/html-dialog-demos/pom.xml, quick-start-tutorial/quick-start-tutorial/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, rule-engine/rule-engine-demos/pom.xml, workflow/workflow-demos-test/pom.xml, workflow/workflow-demos/pom.xml
Raising project-build-plugin version to 11.2.0 / 11.2.1-SNAPSHOT
=> Raising project-build-plugin version to 11.2.0 / 11.2.1-SNAPSHOT

connectivity/connectivity-demos-product/pom.xml, connectivity/connectivity-demos-test/pom.xml, connectivity/connectivity-demos/pom.xml, connectivity/pom.xml, demos-app/demos-app-product/pom.xml, demos-app/demos-app/pom.xml, demos-app/pom.xml, error-handling/error-handling-demos-product/pom.xml, error-handling/error-handling-demos/pom.xml, error-handling/pom.xml, html-dialog/html-dialog-demos-product/pom.xml, html-dialog/html-dialog-demos-test/pom.xml, html-dialog/html-dialog-demos/pom.xml, html-dialog/pom.xml, pom.xml, quick-start-tutorial/pom.xml, quick-start-tutorial/quick-start-tutorial-product/pom.xml, quick-start-tutorial/quick-start-tutorial/pom.xml, rule-engine/pom.xml, rule-engine/rule-engine-demos-product/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, rule-engine/rule-engine-demos/pom.xml, workflow/pom.xml, workflow/workflow-demos-product/pom.xml, workflow/workflow-demos-test/pom.xml, workflow/workflow-demos/pom.xml
Raise version to 11.3.0-SNAPSHOT
=> Raise version to 11.3.0-SNAPSHOT

connectivity/connectivity-demos-test/pom.xml, connectivity/connectivity-demos/pom.xml, error-handling/error-handling-demos/pom.xml, html-dialog/html-dialog-demos-test/pom.xml, html-dialog/html-dialog-demos/pom.xml, quick-start-tutorial/quick-start-tutorial/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, rule-engine/rule-engine-demos/pom.xml, workflow/workflow-demos-test/pom.xml, workflow/workflow-demos/pom.xml
Raising project-build-plugin version to 11.2.0 / 11.3.0-SNAPSHOT
=> Raising project-build-plugin version to 11.2.0 / 11.3.0-SNAPSHOT

.devcontainer/Dockerfile, .devcontainer/devcontainer.json
@ivy-cst do we want to merge that?
=> XIVY-12892 add devcontainer files

connectivity/connectivity-demos-product/pom.xml, connectivity/connectivity-demos-test/pom.xml, connectivity/connectivity-demos/pom.xml, connectivity/pom.xml, demos-app/demos-app-product/pom.xml, demos-app/demos-app/pom.xml, demos-app/pom.xml, error-handling/error-handling-demos-product/pom.xml, error-handling/error-handling-demos/pom.xml, error-handling/pom.xml, html-dialog/html-dialog-demos-product/pom.xml, html-dialog/html-dialog-demos-test/pom.xml, html-dialog/html-dialog-demos/pom.xml, html-dialog/pom.xml, pom.xml, quick-start-tutorial/pom.xml, quick-start-tutorial/quick-start-tutorial-product/pom.xml, quick-start-tutorial/quick-start-tutorial/pom.xml, rule-engine/pom.xml, rule-engine/rule-engine-demos-product/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, rule-engine/rule-engine-demos/pom.xml, workflow/pom.xml, workflow/workflow-demos-product/pom.xml, workflow/workflow-demos-test/pom.xml, workflow/workflow-demos/pom.xml
Raise version to 11.2.2-SNAPSHOT
=> Raise version to 11.2.2-SNAPSHOT

html-dialog/html-dialog-demos-test/src_test/ch/ivyteam/htmldialog/demo/WebTestOutputIT.java, html-dialog/html-dialog-demos/.project, html-dialog/html-dialog-demos/processes/Other.p.json, html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/other/JsfAgnosticFormDemo/JsfAgnosticFormDemo.f.json, html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/other/JsfAgnosticFormDemo/JsfAgnosticFormDemo.rddescriptor, html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/other/JsfAgnosticFormDemo/JsfAgnosticFormDemoData.ivyClass, html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/other/JsfAgnosticFormDemo/JsfAgnosticFormDemoProcess.p.json, html-dialog/html-dialog-demos/webContent/ivy-form/layouts/form.xhtml, html-dialog/html-dialog-demos/webContent/layouts/includes/sidebar.xhtml
works on jenkins ... will have to wait for nightly to get green builds in the actions pipeline
=> XIVY-13627 demonstrate dialog generated from form.j.json

html-dialog/html-dialog-demos-test/src_test/ch/ivyteam/htmldialog/demo/WebTestOutputIT.java
13.0.8
Enter opens a dialog to change the data. Using SPACE now.
=> XIVY-13553 Fix test because of changed behavour between PF 13.0.7 and

rule-engine/rule-engine-demos-test/src_test/ch/ivyteam/rule/engine/demo/TestDiscountCalculator.java, rule-engine/rule-engine-demos/dataclasses/rule/engine/demo/Data.ivyClass, rule-engine/rule-engine-demos/processes/DiscountCalculator.p.json
=> Add IvyProcessTest to rule demo

workflow/workflow-demos/dataclasses/workflow/humantask/ProcurementRequest.ivyClass, workflow/workflow-demos/processes/Humantask/ProcurementRequestDynamic.p.json
=> Add ProcurementRequest demo with dynamic tasks

html-dialog/html-dialog-demos/src/ch/ivyteam/htmldialog/demo/data/DataSource.java
- a filter is a FilterMeta rather than a plain String as it was in previous primefaces versions (ivy8) 
- combine global filter with column filters
=> fix filters in Lazy Loading Table Demo

html-dialog/html-dialog-demos/webContent/layouts/includes/sidebar.xhtml
https://1ivy.atlassian.net/browse/XIVY-14121
=> XIVY-14079 Fix buggy sidebar

html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/input/FileUploadAdvancedModeDemo/FileUploadAdvancedModeDemoProcess.p.json
I will also merge this to 10 and 11.3
=> Change upload demo to write into app cms (iar support)

html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/input/FileUploadAdvancedModeDemo/FileUploadAdvancedModeDemoProcess.p.json
master: https://github.com/axonivy-market/demo-projects/pull/557
=> Support write to app cms (needed if pmv is iar) > R11.3

.github/workflows/ci.yml, html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/input/FileUploadAdvancedModeDemo/FileUploadAdvancedModeDemoProcess.p.json
master: https://github.com/axonivy-market/demo-projects/pull/557
=> Change upload demo to write into app cms (iar support) > R10

connectivity/connectivity-demos-test/pom.xml
=> fix:streamline jersey version

connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/json/BackendLoggerFeature.java
produces logs on calls of the REST backend
[log4j2.xml.zip](https://github.com/user-attachments/files/16961141/log4j2.xml.zip)
=> XIVY-14373 demonstrate a REST backend-logger

html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/offline/ClientSideValidation/ClientSideValidation.xhtml
=> XIVY-13756 fix: add offline renderkit

connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/aynch/SignalInvoker.java
Same as https://github.com/axonivy-market/demo-projects/pull/618
=> replace `IvyAsyncRunner` with `IvyAsyncExecutor` > 10

connectivity/connectivity-demos-test/src_test/rest/bpm/TestAsyncInvocation.java
fix and leave some teaching notes :)
=> harden flacky test: assert graceful up to 10 seconds for the async

connectivity/connectivity-demos-test/pom.xml, connectivity/connectivity-demos/.settings/org.eclipse.core.resources.prefs, connectivity/connectivity-demos/pom.xml, error-handling/error-handling-demos/.settings/org.eclipse.core.resources.prefs, error-handling/error-handling-demos/pom.xml, html-dialog/html-dialog-demos-test/pom.xml, html-dialog/html-dialog-demos/.settings/org.eclipse.core.resources.prefs, html-dialog/html-dialog-demos/pom.xml, quick-start-tutorial/quick-start-tutorial/.settings/org.eclipse.core.resources.prefs, quick-start-tutorial/quick-start-tutorial/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, rule-engine/rule-engine-demos/.settings/org.eclipse.core.resources.prefs, rule-engine/rule-engine-demos/pom.xml, workflow/workflow-demos-test/pom.xml, workflow/workflow-demos/.settings/org.eclipse.core.resources.prefs, workflow/workflow-demos/pom.xml
Seems like this would fix https://1ivy.atlassian.net/browse/XIVY-15447
=> XIVY-15332 Fix import iar cause read-only settings file message

Jenkinsfile
https://github.com/axonivy-market/demo-projects/pull/630
=> Fix deploy on release branch

connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/provider/PersonService.java
leave a small trace that javax.validation is supported
=> XIVY-15555 javax.validation constraints for REST resources

connectivity/connectivity-demos/config/rest-clients.yaml, connectivity/connectivity-demos/dataclasses/rest/customClientData.d.json, connectivity/connectivity-demos/processes/rest/customClient.p.json, connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/client/connect/KeepAliveFeature.java
me and @peters-axon just struggled with corrupt keep-alive setup in fwf-panda ; se we provide a demo how-to define your custom keep-alive strategy.
=> document keep-alive strategy setup

.github/workflows/ci.yml
Update all workflow actions to new version v6
=> Update workflow actions to v6

Jenkinsfile
@alexsuter So geht das Mr Legacy :smiley_cat:
=> Fix docker container name collision

html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/other/JsfAgnosticFormDemo/JsfAgnosticFormDemo.f.json, html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/output/DataTableDemo/DataTableDemo.xhtml, html-dialog/html-dialog-demos/src_hd/ch/ivyteam/htmldialog/demo/output/LazyLoadingDemo/LazyLoadingDemo.xhtml, html-dialog/html-dialog-demos/webContent/ivy-form/layouts/form.xhtml, html-dialog/html-dialog-demos/webContent/layouts/HtmlDemo.xhtml
=> XIVY-16795 Beautify form demo

.ivy/raise-build-plugin-version.sh, .ivy/raise-web-tester.sh, connectivity/connectivity-demos-test/pom.xml, connectivity/connectivity-demos/pom.xml, error-handling/error-handling-demos/pom.xml, html-dialog/html-dialog-demos-test/pom.xml, html-dialog/html-dialog-demos/pom.xml, quick-start-tutorial/quick-start-tutorial/pom.xml, rule-engine/pom.xml, rule-engine/rule-engine-demos-test/pom.xml, rule-engine/rule-engine-demos/pom.xml, workflow/workflow-demos-test/pom.xml, workflow/workflow-demos/pom.xml
- Remove raise-build-plugin-version.sh
- Remove raise-web-tester.sh
- Cleanup pluginManagement (defined in ivy-project-parent)
- Cleanup pluginRepositories (defined in ivy-project-parent)
- Use 13.2.0-SNAPSHOT ivy-project-parent
=> Cleanup ivy-project-parent migration

database/db-demos-test/src_test/db/demo/persistence/test/PlayerRepoIvyTest.java, database/db-demos/.classpath, database/db-demos/config/persistence.xml, database/db-demos/dataclasses/db/demos/persistence/Player.d.json, database/db-demos/pom.xml, database/db-demos/src/db/demos/persistence/PlayerRepo.java
integrating https://github.com/axonivy-market/persistence-demo/, which I'll delete after merging this PR :recycle: .
=> add first simple jakarta.data repository impl

database/db-demos/processes/persistence/persistenceDemo.p.json, database/db-demos/src_hd/db/demos/persistence/PersonsForm/PersonsForm.f.json, database/db-demos/src_hd/db/demos/persistence/PersonsForm/PersonsFormData.d.json, database/db-demos/src_hd/db/demos/persistence/PersonsForm/PersonsFormProcess.p.json
=> XIVY-16223 Enhance db-demos to include Entity Repository via Form Editor

workflow/workflow-demos-test/config/variables.yaml, workflow/workflow-demos-test/src_test/test/bpm/TestCaseCleanup.java, workflow/workflow-demos/config/variables.yaml, workflow/workflow-demos/dataclasses/Maintenance/HouseKeeperData.d.json, workflow/workflow-demos/processes/Maintenance/HouseKeeper.p.json, workflow/workflow-demos/src/ch/ivyteam/ivy/wfdemo/maintenance/CaseChore.java
=> XIVY-17471 document timed case house-keeping

connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/provider/PersonService.java, connectivity/connectivity-demos/src/com/axonivy/connectivity/rest/provider/SecureService.java
https://github.com/axonivy/demo-projects/pull/878
=> Escape user input for rest service > R12
